; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-c3-devkitm-1]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
upload_port = /dev/ttyACM0
monitor_port = /dev/ttyACM0
board_build.partitions = huge_app.csv
upload_protocol = esptool
build_flags =
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
lib_deps = 
	knolleary/PubSubClient@^2.8.0
	dfrobot/DFRobot_Heartrate@^1.0.0
	mbed-goncaloc/ADXL_I2C@0.0.0+sha.a5a2383a6e2f
	dfrobot/DFRobot_BloodOxygen_S@^1.0.0
	dfrobot/DFRobot_RTU@^1.0.6
	adafruit/Adafruit ADXL345@^1.3.4
	adafruit/Adafruit BusIO@^1.17.4
	adafruit/Adafruit Unified Sensor@^1.1.15
	adafruit/Adafruit SH110X@^2.1.9
